/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/mooon.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <directionalLight
          name="Light"
          intensity={10}
          decay={2}
          position={[4.08, 5.9, -1.01]}
          rotation={[-1.84, 0.6, 1.93]}
          userData={{ name: "Light" }}
        >
          <group position={[0, 0, -1]} />
        </directionalLight>
        <PerspectiveCamera
          name="Camera"
          makeDefault={false}
          far={100}
          near={0.1}
          fov={22.9}
          position={[21.1, -0.12, 17.34]}
          rotation={[0.02, 0.89, 1.6]}
          userData={{ name: "Camera" }}
        />
        <mesh
          name="Cube001"
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials["Material.001"]}
          rotation={[2.53, -0.61, -1.93]}
          userData={{ name: "Cube.001" }}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/mooon.glb");
